### PR TITLE
Simplify test setup by using the MOCK_MAILHOST_FIXTURE

### LINKED ISSUE #59: Use the MOCK_MAILHOST_FIXTURE instead of a custom approach
The package tests set up a custom MailHost:
https://github.com/plone/plone.app.contentrules/blob/94c9a1f4062989ecaa17b4aacdc538059f2577aa/plone/app/contentrules/tests/test_action_mail.py#L59-L66
but we have an easier way to do that by using `from plone.app.testing import MOCK_MAILHOST_FIXTURE`.

### PR DESCRIPTION
**Pull request by ale-rt**
Fixes #59

### CODE REVIEW

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
@jaroel this should fix a bunch of tests in the dx site root plip job, e.g.: https://jenkins.plone.org/view/PLIPs/job/plip-dx-siteroot-3.8/24/testReport/junit/plone.app.contentrules.tests.test_action_mail/TestMailAction/testExecute/

**Comment by jaroel** [comment]
> @jaroel this should fix a bunch of tests in the dx site root plip job, e.g.: https://jenkins.plone.org/view/PLIPs/job/plip-dx-siteroot-3.8/24/testReport/junit/plone.app.contentrules.tests.test_action_mail/TestMailAction/testExecute/

Hahahahahaha :D You are amazing!

**Review by jaroel — APPROVED** [review]
lgtm; fixed couple of tests in the DX site root branches, so seems to work!

**Review by mauritsvanrees — APPROVED** [review]
Much better. Thanks!

**Pull request merged**
