### PR TITLE
move to z3c.form

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by gforcada** [comment]
@vangheem I rebased your branch to be on top of master again, could you give it a look? The only conflicts I got were about setup.py and CHANGES.rst, so it should be fine.

Tests are running here: https://github.com/plone/plone.app.discussion/pull/56

**Comment by vangheem** [comment]
Yes, this is going to take me more time to go over. Lots of test fixes yet. I'll try to look at it soon.

**Comment by vangheem** [comment]
Alright, all tests passing for plone.app.contentrules now.

**Comment by tisto** [comment]
http://jenkins.plone.org/job/pull-request/182/

**Pull request merged**
