### PR TITLE
Fix exception about getIcon() not being available

### PR DESCRIPTION
**Pull request by Rudd-O**
Fixes https://github.com/plone/plone.app.contentrules/issues/68

### CODE REVIEW

**Comment by Rudd-O** [comment]
@jenkins-plone-org please run jobs

**Comment by Rudd-O** [comment]
Yo, folks!

https://github.com/plone/plone.app.layout/commit/3370c94570f88cdd3cc43b72c2bee3f7b6daaa23#diff-0455e2a834b501b249bd835b12849c43a221b46e067af1dcb829573f2187f4ee says the icons are rendered as fonts now, and getIcon is deprecated.

What's the proper replacement here???

**Comment by jensens** [comment]
In Plone 6 all changed and icons are SVGs using the new icon registry. docs draft here   https://github.com/plone/documentation/blob/classic-ui/icons.md

**Comment by yurj** [comment]
> In Plone 6 all changed and icons are SVGs using the new icon registry. docs draft here https://github.com/plone/documentation/blob/classic-ui/icons.md

It would be useful to have an example on how to use them without the tag code, statically, so they can be used in diazo index.html for example (an icon for the theme).

**Comment by agitator** [comment]
@yurj https://6-classic.demo.plone.org/++plone++bootstrap-icons/lightning.svg as in the docs ;-)

**Comment by Rudd-O** [comment]
Forgive me for sounding daft, but what do I add to the code change I made, in order to use these SVG icons?  I have no clue whatsoever.

**Comment by agitator** [comment]
@Rudd-O looked into it yesterday and decided to rework the ui... join us on discord #classic-ui tomorrow ;-)

**Comment by Rudd-O** [comment]
Will join.

**Pull request closed without merging**
