### PR TITLE
Controlpanel fixes

### LINKED ISSUE #75: The workflow action edit view uses WorkflowAddForm instead of WorkflowEditForm
The workflow action edit view uses WorkflowAddForm instead of WorkflowEditForm

### LINKED ISSUE #102: dont show the card element in conrolpanel if no rules defined

### LINKED ISSUE #103: dont show tabs in modals
Modals with "global"-tabs:
- edit rule
- edit actions

### PR DESCRIPTION
**Pull request by 1letter**
- fix #75 
- fix #102 
- fix #103 
- fix https://github.com/plone/Products.CMFPlone/issues/4046

### CODE REVIEW

**Comment by 1letter** [comment]
@jenkins-plone-org please run jobs

**Comment by 1letter** [comment]
@jenkins-plone-org please run jobs

**Comment by 1letter** [comment]
@petschki i would add the robot tests in Products.CMFPlone

**Comment by petschki** [comment]
> @petschki i would add the robot tests in Products.CMFPlone

I'd update the doctests here https://github.com/plone/plone.app.contentrules/blob/master/plone/app/contentrules/tests/assignment.txt#L63 ... so we do not depend on another package here.

In general we have to think about the robottests in CMFPlone for version 7.0 ... they should live somewhere in a Classic-UI package (not the distribution `plone.classicui`) ... I could image to move them to `plone.app.layout` as its the designated package for Classic-UI layout/template package (see https://github.com/plone/Products.CMFPlone/issues/3953#issuecomment-2176486376)

**Comment by 1letter** [comment]
> I'd update the doctests

you mean "remove the test" and "convert it to robot tests"?

**Comment by 1letter** [comment]
@jenkins-plone-org please run jobs

**Review by petschki — APPROVED** [review]

**Pull request merged**
