### PR TITLE
Backport "fix genericsetup export with complex properties" to 4.0

### PR DESCRIPTION
**Pull request by JeffersonBledsoe**
[PR #51](https://github.com/plone/plone.app.contentrules/pull/51) fixed some issues with exporting complex properties (such as IDicts). This PR is a backport of those fixes to 4.0.x. for use in Plone 5 versions prior to 5.2.

### CODE REVIEW

**Comment by JeffersonBledsoe** [comment]
@jenkins-plone-org please run jobs

**Comment by JeffersonBledsoe** [comment]
@jenkins-plone-org please run jobs

**Comment by JeffersonBledsoe** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
So, the red test is a flaky robot test, I think. LGTM. Is the `draft` state by intend?

**Comment by JeffersonBledsoe** [comment]
I moved it back to a draft while I was looking into the red tests. I can't reproduce the failure locally so I think it's good to merge if you're happy with it

**Comment by JeffersonBledsoe** [comment]
@jensens Thanks for merging this so swiftly! Any chance of getting a 4.0.20 release with this fix included?

**Comment by jensens** [comment]
@plone/release-team that question above is in your domain

**Comment by mauritsvanrees** [comment]
The red test is *not* a flaky robot test. It is not a robot test and not flaky. It fails for me locally as well:

```
Error in test testExport (plone.app.contentrules.tests.test_configuration.TestGenericSetup)
Traceback (most recent call last):
  File "/Users/maurits/.pyenv/versions/2.7.17/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/maurits/community/plone-coredev/5.1/src/plone.app.contentrules/plone/app/contentrules/tests/test_configuration.py", line 122, in testExport
    body = exporter.body.decode('utf8')
  File "/Users/maurits/shared-eggs/cp27m/Products.GenericSetup-1.8.11-py2.7.egg/Products/GenericSetup/utils.py", line 499, in _exportBody
    xml = self._doc.toprettyxml(' ')
  File "/Users/maurits/.pyenv/versions/2.7.17/lib/python2.7/xml/dom/minidom.py", line 61, in toprettyxml
    return writer.getvalue()
  File "/Users/maurits/.pyenv/versions/2.7.17/lib/python2.7/StringIO.py", line 271, in getvalue
    self.buf += ''.join(self.buflist)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 32: ordinal not in range(128)
```

Note that the current 5.1 job on Jenkins passes because `plone.app.contentrules` is not in the auto-checkouts.

If the test is fixed, I can certainly make a release. Maybe it can still end up in Plone 5.1.7, which is now pending.

**Comment by jensens** [comment]
ops, mea culpa, @JeffersonBledsoe may you fix this soon? Otherwise I revert for now.

**Comment by JeffersonBledsoe** [comment]
Ahh, I wasn't running the tests from the coredev buildout. I can reproduce it now. My bad! I'll get to looking at fixing it today.

**Comment by JeffersonBledsoe** [comment]
@jensens I've narrowed down the issue, but I doubt I will get it fixed today. Would you revert it for now and I'll get a fresh PR ready when the issue is resolved?

**Pull request merged**
