### PR TITLE
Use z3c.form for custom email-action form template

### PR DESCRIPTION
**Pull request by pbauer**

### CODE REVIEW

**Comment by vangheem** [comment]
tests running: http://jenkins.plone.org/job/pull-request-5.0/285/

**Comment by vangheem** [comment]
need to run again, unrelated failure: http://jenkins.plone.org/job/pull-request-5.0/286/

**Comment by vangheem** [comment]
We have test failures

**Comment by pbauer** [comment]
Probably unrelated. But let's go again: http://jenkins.plone.org/job/pull-request-5.0/289/

**Comment by pbauer** [comment]
Test are green.

**Pull request merged**
